services:
  biniou:
    build:
      context: .
      dockerfile: Dockerfile
    image: biniou:latest
    container_name: biniou
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 48G
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 1m
      timeout: 20s
      retries: 3
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "7860:7860"
    volumes:
      - ./workspace/outputs:/home/biniou/biniou/outputs
      - ./workspace/models:/home/biniou/biniou/models
      - ./workspace/cache:/home/biniou/.cache/huggingface
      - ./workspace/gfpgan:/home/biniou/biniou/gfpgan
    restart: unless-stopped
    shm_size: 16gb
    ulimits:
      memlock: -1
      stack: 67108864 
